### ISSUE TITLE
Additional joins are ignored inside an aggregate block with `all` condition

### ISSUE THREAD

**Issue by rhas1** [bcodell/dbt-activity-schema#18]
I'm creating a dataset which needs to consider all available data with multiple join conditions. 

The additional joins work fine when the join condition is set to `before` or `after` but is completely ignored in the `all` condition. 

- Given the syntax here,

```
aggregate all updated_working_hours (
    min(working_date) as next_initial_eval
    filter {{dbt_aql.json_extract('{feature_json}', 'working_date')}}::date > current_timestamp::date
    filter {{dbt_aql.json_extract('{feature_json}', 'available_intake_appointments')}}::float > 0.0
    join {{ dbt_aql.json_extract('{joined}.{feature_json}', 'clinician_id') }} = {primary}.clinician_id
    join {{ dbt_aql.json_extract('{joined}.{feature_json}', 'territory') }} = {primary}.territory
)
```

- The generated code looks like this,

```
joined__aggregate__all__updated_working_hours__4 as (
    -- special join case for aggregate all to improve performance
    select
        j.clinician_id,
sum(cast(nullif(json_extract_path_text(j.attributes, 'current_availability'), '') as FLOAT)) as availability_7_days,
sum(cast(nullif(json_extract_path_text(j.attributes, 'hours_booked'), '') as FLOAT)) as hours_booked_7_days
    from "postgres"."dbt_rukshan"."clinician_stream" j
    where j.activity = 'updated working hours'
        and json_extract_path_text(attributes, 'working_date')::date > current_timestamp::date
        and json_extract_path_text(attributes, 'working_date')::date <= (current_timestamp::date + INTERVAL '7 day')::date 
    group by 1 
)
```

- However, when the join condition is `after` the generated code is,

```
joined__aggregate__after__updated_working_hours__4 as (
    select
        p.req__activity_id,
sum(cast(nullif(json_extract_path_text(j.attributes, 'current_availability'), '') as FLOAT)) as availability_7_days
    from primary__all__updated_working_hours__None__1 as p
    left join "postgres"."dbt_rukshan"."clinician_stream" j
        -- filter joined activity first to improve query performance
        on j.activity = 'updated working hours'
        and p.req__clinician_id = j.clinician_id
        and p.req__activity_at < j.activity_at
        and json_extract_path_text(j.attributes, 'clinician_id') = p.clinician_id
        and json_extract_path_text(j.attributes, 'territory') = p.territory
        and json_extract_path_text(attributes, 'working_date')::date > current_timestamp::date
        and json_extract_path_text(attributes, 'working_date')::date <= (current_timestamp::date + INTERVAL '7 day')::date
    group by 1
)
```

**Comment by bcodell** [comment]
Hey @r-u-k-i-y-a - thanks for posting about this. This behavior is actually by design, as `aggregate_all` relationships can bog down query performance for activities that occur with high frequency. There's documentation about it [here](https://github.com/bcodell/dbt-aql#extra-join-criteria-for-joined-activities).

Can you provide a little more context on what business question you're trying to answer? I see that you're building a dataset that contains 1 row for each `updated_working_hours` activity occurrence, but knowing what business question(s) that dataset will answer will be useful context to figure out an alternate resolution.

**Comment by rhas1** [comment]
Thanks for the quick response @bcodell and apologies for taking so long to reply. 

My requirement was to aggregate a certain column (for example lets say `daily state sales`) to create a `weekly state sales` column and append it to each row of the dataset. Since I needed all data from the main activity with additional joins on `state`, I expected the join feature to work when all occurrences were selected as well. 

For a solution, I was able to cover this up with some raw SQL on the dataset so all is good!

**Comment by bcodell** [comment]
Thanks for the update! Apologies for the delayed reply. This is exactly why I built this project with dbt - when a use case arises that is outside the scope of what this project does, the developer can always fall back on raw SQL. I'm going to close this issue for now - feel free to re-open if there's anything else you want addressed.
