### ISSUE TITLE
feature - Allow config of partition column granularity (BigQuery)

### ISSUE THREAD

**Issue by awoehrl** [bcodell/dbt-activity-schema#32]
Right now the granularity of the BigQuery partitions is set to "MONTH". It would be great if this becomes a config option. We usually have to set our tables to "DAY".

**Comment by bcodell** [comment]
Great suggestion! I think this customization can be solved by creating a custom `cluster_keys` macro in the project, and then defining the appropriate namespace search order (docs here: https://docs.getdbt.com/reference/project-configs/dispatch-config).

Would you be open to trying it out and seeing if it works? Happy to take it on myself if not. Either way, if it works, I can update the documentation to show this example as a best practice.

Side note - does it seem reasonable to solve this as a project-specific override? Or do you think users will need to override this specific parameter often enough that a dedicated interface should be built for it? For example, if, for a single project, some streams should be partitioned by date and others should be partitioned by month, then the better solution would be to define as a stream-specific configuration in the dbt_project.yml variables.

**Comment by awoehrl** [comment]
That's a great idea! Yes, I think it's totally reasonable to do an override. Thinking about it more, in the end it's always possible to set the cluster and partition keys via the model's config block and hard code the actual column names there.

**Comment by awoehrl** [comment]
I just did a test run with a custom `cluster_keys` macro and it worked like charm. I believe you don't even need to change the namespace search order as the root project is first anyways.

**Comment by bcodell** [comment]
Per discussion with @awoehrl - suggested override works fine enough for now - allows developer to tailor partition requirements by activity too (e.g. pageview needs daily but most other activities are fine with monthly). Will close for now and consider revisiting if a similar request pops up down the road.
