### ISSUE TITLE
feature - dataset joins should coalesce customer_id and anonymous_customer_id

### ISSUE THREAD

**Issue by awoehrl** [bcodell/dbt-activity-schema#33]
Dataset joins right now only use `customer_id` for joins. This could be extended to a coalesce that uses `anonymous_customer_id` when `customer_id` is null.

Since anonymous_customer_id is an optional field, there needs to be a check implemented.

Things to consider:
- How does this impact performance?
- Are there alternatives. E.g. using one merged id column instead of two throughout the activities

**Comment by bcodell** [comment]
Relates to #34 and #47 and #49
Current use case is bespoke sql on user stream to do counts of different types of users (unknown, registered/unpaid, registered/paid)

Takeaways with @awoehrl:
* Will build first-class support for anonymous ID in the package
* @awoehrl to build an article stream (and/or publication stream) to enable aggregations of user counts at the article level
